### ISSUE TITLE
Urgent! Request structure BAD when updating resource's relationships

### ISSUE THREAD

**Issue by subotkevic** [milroyfraser/sarala#17]
Basically, when I'm trying to update resource A with it's relationships (hasMany) say B's:

It puts B's attributes inside `included` object, but JSON spec says that related data, when updating parent resouce, should be included inside `relationships` object.

Like this:
https://jsonapi.org/format/#crud-updating-resource-relationships

**Comment by asadhshujau** [comment]
did u solve this ? if so how ? im having the same problem

**Comment by subotkevic** [comment]
It turns out that JSON API spec doesn’t support updating relationships in single request. You can only link/sync the ID’s of those relationships.
