### ISSUE TITLE
Have to access relation through .data?

### ISSUE THREAD

**Issue by zlanich** [milroyfraser/sarala#19]
I'm in the process of mocking a front-end dashboard, and I'm feeding fake data into Sarala. I have the following relationship structure:

User
- relationships
-- parkingAuthorities

Once the data comes back, I can't just access user.parkingAuthorities to get the relationship collection. I have to to access user.parkingAuthorities.data. This seems odd and doesn't follow the Laravel relationship collection pattern. 

Is this intended? Am I perhaps doing something wrong?

There's no documentation on how to actually use/access the relationships; just on how to define them and fetch them.

**Comment by milroyfraser** [comment]
Hi @zlanich,

It is documented here at the bottom of the page: https://sarala-io.github.io/sarala-js-docs/guide/model/define-relationships.html

**Comment by zlanich** [comment]
Ah! I somehow missed the destructuring assignment there. Thank you!
