### ISSUE TITLE
No Support for Persist Requests with No Content

### ISSUE THREAD

**Issue by aidan-casey** [milroyfraser/sarala#28]
The makePersistRequest function assumes there will be data on return, which will in turn throw an error when making a POST or DELETE request that returns 204 as listed in the JSON:API specification. This should be an easy fix, by just checking the response code before making a return.

A possibility I'm toying with is adding the below to the function. Just have to make sure that wouldn't cause any problems.

```javascript
if (response.status === 204) {
    return this.respond(this.clone())
}
```

https://jsonapi.org/format/#crud-creating
https://jsonapi.org/format/#crud-deleting

**Comment by milroyfraser** [comment]
Hi @aidan-casey,

I don't see any problem with your solution. Could you PR?

Tnx

**Comment by aidan-casey** [comment]
Sure thing, @milroyfraser. Let me draft that up real quick.
