### ISSUE TITLE
Can't resolve 'sarala'

### ISSUE THREAD

**Issue by subotkevic** [milroyfraser/sarala#5]
Hello, looks like npm package is broken, fresh installed package can't be resolved:

```
This dependency was not found:

* sarala in ./src/models/BaseModel.js

To install it, you can run: npm install --save sarala
```

Looks like `build` folder is missing after `npm install`. 
Published wrong way, I believe.

**Comment by subotkevic** [comment]
Previous version installs fine. Current version is published incorrectly for sure.

**Comment by milroyfraser** [comment]
@subotkevic Tnx for reporting. issue fixed. please install latest ✌️
